name: Hotel Lock Code Generator

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-lock-codes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run lock code generator
      run: |
        python improved_phone_generator.py
        
    - name: Upload CSV reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lock-code-reports-${{ github.run_number }}
        path: "*.csv"
        retention-days: 30
        
    - name: Commit and push reports (optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv || true
        git commit -m "Auto-generated lock codes $(date)" || true
        git push || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
